#!/usr/bin/env bash
#Script that displays listening ports that only shows listening sockets
#and that shows the PID and name of the program to which each socket belongs

#-l → listening sockets only
#-p → displays the PID and the program name

netstat -lp
