#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine it’s executed on

if ifconfig &>/dev/null; then
    ifconfig | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
else
    echo "ifconfig command not found"
    exit 1
fi
